import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Navbar } from '../_components/custom/navbar'
import { ThemeProvider } from '../_components/providers/theme-provider'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="w-full 2xl:container h-full mx-auto">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
